# Initially snatched and adapted from libsodium .travis.yml

sudo: false

language: cpp

cache: ccache

os:
 - linux
 
addons:
  apt:
    packages:
    - libcxxtools-dev

before_script:
 - ./autogen.sh

script:
 - ./configure --disable-dependency-tracking
 - make distcheck
 - make distclean > /dev/null
 - ./configure --disable-dependency-tracking --enable-minimal
 - make distcheck
